"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
type Player={id:string;displayName:string;cash:number;ready:boolean;isHost:boolean;portfolioValue:number;invested:number;netWorth:number};
type Company={id:string;name:string;tagline:string;sector:string;founder:string;askCash:number;askEquity:number;summary:string;story:string;businessModel:string;risks:string[];facts:Record<string,string>;qa:[string,string][];submittedIds:string[];myBid:{cash:number;equity:number;passed:boolean}|null;finalist:boolean;feedback:"higher"|"lower"|null;result:any};
type State={roomCode:string;status:string;phase:string;phaseNumber:number;totalPhases:number;companiesPerPhase:number;companies:Company[];players:Player[];myPlayerId:string;isHost:boolean};
const money=(n:number)=>new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0}).format(n);
const pct=(n:number)=>`${Number(n).toFixed(Number.isInteger(n)?0:1)}%`;
function readSession(){try{return JSON.parse(localStorage.getItem("shark-syndicate-session-v2")||"null");}catch{return null;}}
function saveSession(s:any){localStorage.setItem("shark-syndicate-session-v2",JSON.stringify(s));}
async function api<T>(url:string,options:RequestInit={},token?:string):Promise<T>{const r=await fetch(url,{...options,cache:"no-store",headers:{"Content-Type":"application/json",...(token?{"x-player-token":token}:{}),...(options.headers||{})}});const p=await r.json().catch(()=>({}));if(!r.ok)throw new Error(p.error||"Something went wrong.");return p;}
export default function Home(){const[session,setSession]=useState<any>(null);const[state,setState]=useState<State|null>(null);const[error,setError]=useState("");const[busy,setBusy]=useState(false);const[name,setName]=useState("");const[roomCode,setRoomCode]=useState("");const[drafts,setDrafts]=useState<Record<string,{cash:string;equity:string}>>({});const[open,setOpen]=useState<string|null>(null);
useEffect(()=>{setSession(readSession());},[]);useEffect(()=>{if(!session)return;let off=false,t:any;const refresh=async()=>{try{const s=await api<State>(`/api/games/${session.roomCode}/state`,{},session.playerToken);if(!off){setState(s);setError("");}}catch(e:any){if(!off)setError(e.message);}finally{if(!off)t=setTimeout(refresh,1500);}};refresh();return()=>{off=true;clearTimeout(t);};},[session]);
const me=useMemo(()=>state?.players.find(p=>p.id===state.myPlayerId),[state]);
async function create(e:FormEvent){e.preventDefault();setBusy(true);try{const s=await api<any>("/api/games",{method:"POST",body:JSON.stringify({displayName:name})});saveSession(s);setSession(s);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
async function join(e:FormEvent){e.preventDefault();setBusy(true);try{const s=await api<any>(`/api/games/${roomCode.trim().toUpperCase()}/join`,{method:"POST",body:JSON.stringify({displayName:name})});saveSession(s);setSession(s);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
async function action(path:string,body:any={}){if(!session)return;setBusy(true);try{await api(`/api/games/${session.roomCode}/${path}`,{method:"POST",body:JSON.stringify(body)},session.playerToken);setState(await api<State>(`/api/games/${session.roomCode}/state`,{},session.playerToken));}catch(e:any){setError(e.message);}finally{setBusy(false);}}
function leave(){localStorage.removeItem("shark-syndicate-session-v2");setSession(null);setState(null);}
if(!session)return <main className="shell landing"><section className="hero"><div className="eyebrow">Multiplayer venture strategy</div><h1>Shark Syndicate</h1><p>Study the companies, build a portfolio, survive a top-two bidding runoff, and finish with the highest net worth.</p></section>{error&&<div className="notice bad">{error}</div>}<div className="home-grid"><form className="panel" onSubmit={create}><div className="eyebrow">Host</div><h2>Create a game</h2><label>Your name<input required value={name} onChange={e=>setName(e.target.value)}/></label><button className="primary" disabled={busy}>Create game</button></form><form className="panel" onSubmit={join}><div className="eyebrow">Player</div><h2>Join a game</h2><label>Your name<input required value={name} onChange={e=>setName(e.target.value)}/></label><label>Room code<input required value={roomCode} onChange={e=>setRoomCode(e.target.value.toUpperCase())}/></label><button disabled={busy}>Join room</button></form></div></main>;
if(!state)return <main className="shell"><div className="panel">Connecting… {error}</div></main>;
const header=<header className="topbar"><div className="brand"><strong>Shark Syndicate</strong><span>Room {state.roomCode}</span></div><button className="ghost" onClick={leave}>Leave</button></header>;
if(state.status==="lobby")return <main className="shell">{header}{error&&<div className="notice bad">{error}</div>}<section className="panel lobby-panel"><div><div className="eyebrow">Lobby</div><h1>Room {state.roomCode}</h1><p>2 players: 3 phases × 3 companies. 3–4 players: 2 × 4. 5–6 players: 2 × 5.</p></div><div className="player-list">{state.players.map(p=><div className="player-row" key={p.id}><strong>{p.displayName}{p.isHost&&<span className="tag">Host</span>}</strong><span className={p.ready?"ready":"muted"}>{p.ready?"Ready":"Not ready"}</span></div>)}</div><div className="button-row"><button className={!me?.ready?"primary":""} onClick={()=>action("ready",{ready:!me?.ready})}>{me?.ready?"Mark not ready":"I’m ready"}</button>{state.isHost&&<button className="primary" disabled={state.players.length<2||state.players.length>6||!state.players.every(p=>p.ready)} onClick={()=>action("start")}>Start game</button>}</div></section></main>;
const standings=[...state.players].sort((a,b)=>b.netWorth-a.netWorth);
if(state.status==="finished")return <main className="shell">{header}<section className="hero compact"><div className="eyebrow">Final standings</div><h1>{standings[0]?.displayName} wins</h1></section><Leaderboard players={standings}/>{state.isHost&&<button className="primary" onClick={()=>action("restart")}>Play again</button>}</main>;
if(state.phase==="intermission")return <main className="shell">{header}<section className="hero compact"><div className="eyebrow">Between phases</div><h1>Reassess the table</h1><p>Phase {state.phaseNumber} results are now public. Use the standings to decide who you trust, who has cash, and who may be worth partnering with next.</p></section><Leaderboard players={standings}/><section className="panel intermission"><h2>Ready for Phase {state.phaseNumber+1}?</h2><button className={!me?.ready?"primary":""} onClick={()=>action("ready",{ready:!me?.ready})}>{me?.ready?"Mark not ready":"I’m ready"}</button>{state.isHost&&<button className="primary" disabled={!state.players.every(p=>p.ready)} onClick={()=>action("next")}>Begin next phase</button>}</section></main>;
const round=state.phase==="round1"?1:state.phase==="round2"?2:null;return <main className="shell">{header}{error&&<div className="notice bad">{error}</div>}<div className="game-topline"><span>Phase {state.phaseNumber} of {state.totalPhases} · {round?`Bidding Round ${round}`:"Results"}</span><strong>Your cash: {money(me?.cash||0)}</strong></div><section className="portfolio-strip"><Metric label="Cash" value={money(me?.cash||0)}/><Metric label="Invested" value={money(me?.invested||0)}/><Metric label="Portfolio" value={money(me?.portfolioValue||0)}/><Metric label="Gain / loss" value={money((me?.portfolioValue||0)-(me?.invested||0))}/><Metric label="Net worth" value={money(me?.netWorth||0)}/></section><div className="company-grid">{state.companies.map((c,i)=><article className="panel company-tile" key={c.id}><div className="tile-head"><div><span className="sector">{c.sector}</span><h2>{c.name}</h2><p>{c.tagline}</p></div><button className="ghost small" onClick={()=>setOpen(open===c.id?null:c.id)}>{open===c.id?"Less":"Research"}</button></div><div className="ask mini"><span>THE ASK</span><strong>{money(c.askCash)} for {pct(c.askEquity)}</strong></div>{open===c.id&&<div className="research"><p>{c.summary}</p><h4>Founder</h4><p>{c.founder}: {c.story}</p><h4>Business model</h4><p>{c.businessModel}</p><div className="fact-grid">{Object.entries(c.facts).map(([k,v])=><Metric key={k} label={k} value={v}/>)}</div><h4>Key risks</h4><p>{c.risks.join(" · ")}</p></div>}{round&&<BidBox company={c} slot={i} round={round} me={me!} players={state.players} busy={busy} drafts={drafts} setDrafts={setDrafts} action={action}/>} {state.phase==="phase_result"&&<Result company={c}/>}</article>)}</div>{state.isHost&&round&&<button className="primary advance" onClick={()=>action("resolve")}>{round===1?"Close Round 1 and name finalists":"Resolve all deals"}</button>}{state.phase==="phase_result"&&<><Leaderboard players={standings}/>{state.isHost&&<button className="primary advance" onClick={()=>action("next")}>{state.phaseNumber>=state.totalPhases?"Show final standings":"Continue to intermission"}</button>}</>}</main>;
}
function BidBox({company,slot,round,me,players,busy,drafts,setDrafts,action}:any){const d=drafts[company.id]||{cash:String(company.askCash),equity:String(company.askEquity)};const submitted=company.myBid;const eligible=round===1||company.finalist;if(!eligible)return <div className="notice mutedbox">You did not advance to this runoff.</div>;return <div className="bidbox">{round===2&&<div className={`feedback ${company.feedback}`}>Your Round 1 offer is {company.feedback} than the other finalist.</div>}{submitted?<div className="notice good">{submitted.passed?"Passed":`${money(submitted.cash)} for ${pct(submitted.equity)} locked`}</div>:<><label>Cash offered<input type="number" value={d.cash} onChange={e=>setDrafts({...drafts,[company.id]:{...d,cash:e.target.value}})}/></label><label>Equity requested<input type="number" step="0.5" value={d.equity} onChange={e=>setDrafts({...drafts,[company.id]:{...d,equity:e.target.value}})}/></label><div className="button-row"><button className="primary" disabled={busy} onClick={()=>action("bid",{companySlot:slot,cash:Number(d.cash),equity:Number(d.equity)})}>Submit bid</button><button disabled={busy} onClick={()=>action("pass",{companySlot:slot})}>Pass</button></div></>}<small>{company.submittedIds.length} of {round===1?players.length:Math.min(2,players.length)} decisions locked</small></div>}
function Result({company}:any){const r=company.result;return <div className="result"><div className="eyebrow">Historical result</div><h3>{r.winner?r.winner.playerName+" wins":"No deal"}</h3>{r.winner&&<><strong>{money(r.winner.cash)} for {pct(r.winner.equity)}</strong><p>Stake value: {money(r.winner.currentValue)}</p></>}<p>Actual accepted deal: {money(r.actualDealCash)} for {pct(r.actualDealEquity)}</p><p>{r.outcome.note}</p></div>}
function Metric({label,value}:{label:string;value:string}){return <div className="metric" title={`${label}: use this metric to compare the opportunity and your portfolio position.`}><span>{label} ⓘ</span><strong>{value}</strong></div>}
function Leaderboard({players}:{players:Player[]}){return <section className="panel leaderboard"><h2>Leaderboard</h2>{players.map((p,i)=><div className="standing-row" key={p.id}><span className="rank">#{i+1}</span><strong>{p.displayName}</strong><span>Cash {money(p.cash)}</span><span>Invested {money(p.invested)}</span><span>Portfolio {money(p.portfolioValue)}</span><strong>{money(p.netWorth)}</strong></div>)}</section>}
