export type Company = {
  id: string;
  name: string;
  tagline: string;
  sector: string;
  founder: string;
  askCash: number;
  askEquity: number;
  actualDealCash: number;
  actualDealEquity: number;
  summary: string;
  story: string;
  businessModel: string;
  risks: string[];
  facts: Record<string, string>;
  qa: [string, string][];
  outcome: { value: number; note: string };
};

const C = (company: Company) => company;

export const COMPANIES: Company[] = [
  C({ id:"meal-mate", name:"MealMate", tagline:"A modular meal-prep system", sector:"Consumer", founder:"Nina Patel", askCash:150000, askEquity:10, actualDealCash:200000, actualDealEquity:20, summary:"Stackable containers designed for portion control and easy transport.", story:"Nina built MealMate after struggling to carry a full day of meals during hospital shifts.", businessModel:"Direct-to-consumer bundles plus wholesale retail accounts.", risks:["Crowded category","Inventory requirements","Retail margin pressure"], facts:{"Lifetime sales":"$620K","Trailing revenue":"$410K","Gross margin":"68%","Distribution":"DTC + 80 stores"}, qa:[["Unit cost?","$8.40 landed"],["Average selling price?","$34"],["Protected?","Design patent issued"],["Use of funds?","Inventory and retail expansion"]], outcome:{value:18000000,note:"A later financing implied an $18M valuation."} }),
  C({ id:"trail-light", name:"TrailLight", tagline:"Emergency lighting for the outdoors", sector:"Outdoor", founder:"Marcus Lee", askCash:250000, askEquity:8, actualDealCash:300000, actualDealEquity:15, summary:"A rechargeable lantern and emergency charging system for hikers and campers.", story:"Marcus designed the first prototype after a multi-day power outage during a backcountry trip.", businessModel:"Online sales, specialty outdoor retail, and corporate emergency kits.", risks:["Inventory-heavy growth","Seasonality","Large incumbents"], facts:{"Lifetime sales":"$1.2M","Trailing revenue":"$760K","Gross margin":"61%","AOV":"$89"}, qa:[["CAC?","$27"],["Profitable?","Slightly profitable"],["Main channel?","Online and outdoor retail"],["Primary risk?","Inventory-heavy growth"]], outcome:{value:32000000,note:"The company was later acquired for a reported $32M."} }),
  C({ id:"splash-safe", name:"SplashSafe", tagline:"A visibility wearable for children", sector:"Safety", founder:"Alicia Gomez", askCash:100000, askEquity:12, actualDealCash:100000, actualDealEquity:25, summary:"A brightly colored water-safety wearable intended to improve child visibility.", story:"Alicia, a former swim instructor, developed the product after years teaching water safety.", businessModel:"One-time consumer purchases through DTC and pool-supply retailers.", risks:["Low repeat purchase","Product-liability exposure","Unproven retail demand"], facts:{"Lifetime sales":"$190K","Trailing revenue":"$120K","Gross margin":"74%","Distribution":"Online only"}, qa:[["Patent?","Utility patent pending"],["Repeat purchase?","Low"],["Retail interest?","Two pilots"],["Founder background?","Former swim instructor"]], outcome:{value:0,note:"The company later ceased operations."} }),
  C({ id:"quiet-cup", name:"QuietCup", tagline:"A better travel mug lid", sector:"Consumer", founder:"Evan Brooks", askCash:180000, askEquity:15, actualDealCash:200000, actualDealEquity:22, summary:"A redesigned lid intended to reduce spills and drinking noise.", story:"Evan created the product after repeatedly spilling coffee during his train commute.", businessModel:"Branded products plus licensing opportunities with drinkware manufacturers.", risks:["Easy to imitate","Dependence on licensing","Excess inventory"], facts:{"Lifetime sales":"$870K","Trailing revenue":"$540K","Gross margin":"72%","Inventory":"$210K at cost"}, qa:[["Retail sell-through?","Strong in top stores"],["Manufacturing?","Domestic contractor"],["Licensing interest?","One inquiry"],["Return rate?","3.1%"]], outcome:{value:11000000,note:"A later disclosed round implied an $11M valuation."} }),
  C({ id:"pet-patch", name:"PetPatch", tagline:"Subscription wellness for dogs", sector:"Pet", founder:"Dana Kim", askCash:300000, askEquity:10, actualDealCash:350000, actualDealEquity:18, summary:"A monthly pet wellness product sold through subscriptions and veterinary partners.", story:"Dana developed the concept while managing chronic skin irritation in her rescue dog.", businessModel:"Recurring subscriptions with veterinarian referral partnerships.", risks:["Churn","Claims scrutiny","Customer acquisition costs"], facts:{"Lifetime sales":"$2.1M","Trailing revenue":"$1.4M","Gross margin":"58%","Recurring revenue":"72%"}, qa:[["Monthly churn?","6.5%"],["Vet distribution?","42 clinics"],["Regulatory concern?","Non-medicated"],["Use of funds?","Sales and inventory"]], outcome:{value:45000000,note:"A later institutional round implied a $45M valuation."} }),
  C({ id:"desk-garden", name:"DeskGarden", tagline:"A self-watering desktop planter", sector:"Home", founder:"Ravi Shah", askCash:125000, askEquity:15, actualDealCash:150000, actualDealEquity:25, summary:"A compact self-watering planter for offices and apartments.", story:"Ravi wanted a planter that could survive frequent business travel and small-space living.", businessModel:"DTC sales, corporate gifting, and seasonal retail placements.", risks:["Holiday concentration","Crowded market","Low purchase frequency"], facts:{"Lifetime sales":"$340K","Trailing revenue":"$230K","Gross margin":"64%","Corporate gifting":"30%"}, qa:[["Seasonality?","Holiday-heavy"],["Return rate?","4.2%"],["Main channel?","DTC"],["Competition?","Crowded but fragmented"]], outcome:{value:9000000,note:"The company was later acquired for a reported $9M."} }),
  C({ id:"fresh-fold", name:"FreshFold", tagline:"Plastic-free laundry sheets", sector:"Household", founder:"Tara Wilson", askCash:200000, askEquity:10, actualDealCash:250000, actualDealEquity:20, summary:"Concentrated detergent sheets shipped in lightweight recyclable packaging.", story:"Tara launched FreshFold to reduce the plastic and shipping weight of detergent jugs.", businessModel:"Subscription-first DTC with growing grocery distribution.", risks:["High CAC","Commodity competition","Subscription fatigue"], facts:{"Annual revenue":"$980K","Gross margin":"66%","Subscribers":"8,400","Monthly churn":"5.8%"}, qa:[["Manufacturing?","Contract manufacturer"],["CAC?","$34"],["AOV?","$42"],["Retail tests?","Three regional chains"]], outcome:{value:24000000,note:"The brand expanded nationally and later raised at a $24M valuation."} }),
  C({ id:"snap-seat", name:"SnapSeat", tagline:"A portable ergonomic seat", sector:"Outdoor", founder:"Jordan Price", askCash:175000, askEquity:12, actualDealCash:200000, actualDealEquity:30, summary:"A lightweight folding seat for festivals, sporting events, and outdoor use.", story:"Jordan built the first SnapSeat after a long weekend at a music festival with no seating.", businessModel:"DTC plus event, sporting-goods, and promotional channels.", risks:["Patent enforcement","Seasonality","Bulky shipping"], facts:{"Lifetime sales":"$510K","Gross margin":"55%","Retail doors":"140","Return rate":"6.1%"}, qa:[["Patent?","Utility patent granted"],["Landed cost?","$19"],["Retail price?","$69"],["Profitable?","Break-even"]], outcome:{value:6500000,note:"The company remained a profitable niche brand valued near $6.5M."} }),
  C({ id:"bright-bite", name:"BrightBite", tagline:"High-protein breakfast bites", sector:"Food", founder:"Maya Chen", askCash:300000, askEquity:8, actualDealCash:300000, actualDealEquity:15, summary:"Shelf-stable breakfast bites targeting busy professionals and families.", story:"Maya created the recipe while looking for a portable breakfast with less sugar.", businessModel:"Natural grocery, club stores, and online multipacks.", risks:["Slotting fees","Spoilage","Thin food margins"], facts:{"Annual revenue":"$1.8M","Gross margin":"42%","Retail doors":"620","Growth":"86% YoY"}, qa:[["Shelf life?","Nine months"],["Repeat rate?","38%"],["Largest customer?","18% of sales"],["Use of funds?","Production run"]], outcome:{value:38000000,note:"The company later sold a majority stake at an estimated $38M valuation."} }),
  C({ id:"loop-lock", name:"LoopLock", tagline:"A smart reusable bike lock", sector:"Mobility", founder:"Theo Martin", askCash:400000, askEquity:10, actualDealCash:500000, actualDealEquity:25, summary:"A connected bike lock with theft alerts and optional recovery coverage.", story:"Theo started LoopLock after having two commuter bikes stolen in one year.", businessModel:"Hardware margin plus a monthly protection subscription.", risks:["Hardware defects","Insurance economics","Long sales cycle"], facts:{"Preorders":"$740K","Gross margin":"49%","Subscribers":"2,100","Patents":"2 pending"}, qa:[["Shipping?","In four months"],["Subscription?","$8/month"],["Battery life?","Six months"],["Insurance partner?","Pilot signed"]], outcome:{value:0,note:"Manufacturing delays exhausted the company's capital and it shut down."} }),
  C({ id:"calm-cloud", name:"CalmCloud", tagline:"Guided sleep audio for families", sector:"Digital", founder:"Leah Morgan", askCash:250000, askEquity:7, actualDealCash:250000, actualDealEquity:12, summary:"A subscription app offering sleep stories and routines for children and parents.", story:"Leah, a pediatric sleep coach, transformed her client routines into an app.", businessModel:"Freemium app with annual family subscriptions and employer benefits distribution.", risks:["App-store dependence","Content costs","Low switching barriers"], facts:{"ARR":"$920K","Gross margin":"88%","Paid families":"14,200","Monthly churn":"3.2%"}, qa:[["CAC?","$31"],["Annual plan?","$79"],["Organic acquisition?","54%"],["Team size?","Seven"]], outcome:{value:52000000,note:"The company was acquired by a wellness platform for approximately $52M."} }),
  C({ id:"carry-kind", name:"CarryKind", tagline:"Adaptive bags for mobility devices", sector:"Accessibility", founder:"Sam Rivera", askCash:150000, askEquity:12, actualDealCash:175000, actualDealEquity:20, summary:"Stylish bags designed to attach securely to wheelchairs, walkers, and scooters.", story:"Sam designed CarryKind with his sister after finding few functional, attractive options.", businessModel:"DTC sales and partnerships with rehabilitation suppliers.", risks:["Niche market","Reimbursement uncertainty","Small production runs"], facts:{"Annual revenue":"$360K","Gross margin":"63%","Repeat rate":"21%","Wholesale":"28% of sales"}, qa:[["Patents?","Attachment design pending"],["Average order?","$96"],["Profitable?","Yes, modestly"],["Use of funds?","New product line"]], outcome:{value:12000000,note:"The company grew steadily and later raised at a $12M valuation."} }),
  C({ id:"pure-pour", name:"PurePour", tagline:"A countertop water flavor system", sector:"Beverage", founder:"Owen Grant", askCash:500000, askEquity:8, actualDealCash:500000, actualDealEquity:20, summary:"A countertop appliance dispensing unsweetened natural flavor concentrates.", story:"Owen created PurePour to help his family drink less soda without relying on sweeteners.", businessModel:"Appliance sales followed by high-margin flavor cartridge subscriptions.", risks:["Appliance reliability","Capital intensity","Repeat cartridge demand"], facts:{"Kickstarter":"$1.1M","Gross margin":"51%","Preorders":"7,800","Cartridge margin":"78%"}, qa:[["Ship date?","Six months"],["Patents?","Three pending"],["Retail interest?","National buyer meeting"],["Cash needed for?","Tooling"]], outcome:{value:68000000,note:"Strong consumables revenue supported a later $68M valuation."} }),
  C({ id:"tiny-tutor", name:"TinyTutor", tagline:"Screen-free language learning", sector:"Education", founder:"Priya Desai", askCash:225000, askEquity:10, actualDealCash:250000, actualDealEquity:18, summary:"Audio-enabled learning cards that teach early language skills without screens.", story:"Priya, a speech-language pathologist, built TinyTutor for multilingual families.", businessModel:"Starter kits, expansion card packs, and school distribution.", risks:["Hardware complexity","Education procurement","Copycats"], facts:{"Lifetime sales":"$780K","Gross margin":"59%","Repeat purchase":"44%","School pilots":"26"}, qa:[["Ages?","Two to seven"],["Languages?","Four currently"],["Patent?","Provisional filed"],["Retail?","Two chains testing"]], outcome:{value:29000000,note:"The company expanded internationally and raised at a $29M valuation."} }),
  C({ id:"good-grip", name:"GoodGrip", tagline:"Kitchen tools for limited dexterity", sector:"Accessibility", founder:"Helen Park", askCash:120000, askEquity:15, actualDealCash:150000, actualDealEquity:25, summary:"Ergonomic kitchen tools designed for people with arthritis or limited hand strength.", story:"Helen, an occupational therapist, created the line for patients who wanted attractive tools.", businessModel:"DTC, medical-supply wholesale, and senior-living partnerships.", risks:["Small addressable niche","Retail education","SKU complexity"], facts:{"Annual revenue":"$410K","Gross margin":"62%","Wholesale":"46%","SKUs":"12"}, qa:[["Clinical evidence?","User testing with 80 adults"],["Patents?","Two design patents"],["AOV?","$74"],["Profitable?","Yes"]], outcome:{value:15000000,note:"A strategic kitchenware company acquired the brand for about $15M."} })
];

export function randomizedCompanyIds(count = COMPANIES.length) {
  return [...COMPANIES].sort(() => Math.random() - 0.5).slice(0, count).map(c => c.id);
}
export function findCompany(id: string | undefined | null) { return COMPANIES.find(c => c.id === id) || null; }
export function gameFormat(players: number) {
  if (players <= 2) return { phases: 3, companiesPerPhase: 3 };
  if (players <= 4) return { phases: 2, companiesPerPhase: 4 };
  return { phases: 2, companiesPerPhase: 5 };
}
