import { NextRequest } from "next/server";
import { findCompany } from "../../../../../lib/companies";
import { authenticatePlayer,bidEntityKey,impliedValue,jsonError,phaseCompanyIds } from "../../../../../lib/game";

export async function GET(request:NextRequest,context:{params:Promise<{roomCode:string}>}){try{
 const{roomCode}=await context.params;const{supabase,game,player}=await authenticatePlayer(roomCode,request);
 const{data:players,error:pe}=await supabase.from("game_players").select("id,display_name,cash,ready,is_host,created_at").eq("game_id",game.id).order("created_at");if(pe)throw pe;
 const{data:bids}=await supabase.from("bids").select("*").eq("game_id",game.id).eq("phase_number",game.phase_number);
 const{data:investments}=await supabase.from("investments").select("*").eq("game_id",game.id);
 const{data:syndicates}=await supabase.from("syndicates").select("*").eq("game_id",game.id).eq("phase_number",game.phase_number).order("created_at");
 const syndicateIds=(syndicates||[]).map(s=>s.id);const{data:members}=syndicateIds.length?await supabase.from("syndicate_members").select("*").in("syndicate_id",syndicateIds):{data:[] as any[]};
 const mySyndicateIds=new Set((members||[]).filter(m=>m.player_id===player.id).map(m=>m.syndicate_id));
 const{data:messages}=mySyndicateIds.size?await supabase.from("syndicate_messages").select("*").in("syndicate_id",Array.from(mySyndicateIds)).order("created_at"):{data:[] as any[]};
 const round=game.phase==="round2"?2:1;const ids=phaseCompanyIds(game);
 const companies=ids.map((id:string,slot:number)=>{const c=findCompany(id);if(!c)return null;const companyBids=(bids||[]).filter(b=>b.company_slot===slot&&b.bidding_round===round);const myEntityKeys=new Set([`p:${player.id}`,...(syndicates||[]).filter(s=>s.leader_id===player.id&&s.status==="active").map(s=>`s:${s.id}`)]);const myBid=companyBids.find(b=>myEntityKeys.has(bidEntityKey(b)));let finalist=false,feedback:null|"higher"|"lower"=null;if(game.phase==="round2"){const r1=(bids||[]).filter(b=>b.company_slot===slot&&b.bidding_round===1&&!b.passed).sort((a,b)=>impliedValue(b)-impliedValue(a)||new Date(a.created_at).getTime()-new Date(b.created_at).getTime()).slice(0,2);const mine=r1.find(b=>myEntityKeys.has(bidEntityKey(b)));finalist=Boolean(mine);if(mine&&r1.length===2)feedback=bidEntityKey(r1[0])===bidEntityKey(mine)?"higher":"lower";}
 const invs=(investments||[]).filter(i=>i.phase_number===game.phase_number&&i.company_slot===slot);let winner:any=null;if(invs.length){const syndicateId=invs[0].syndicate_id;if(syndicateId){const syn=(syndicates||[]).find(s=>s.id===syndicateId);winner={playerId:null,playerName:syn?.name||"Syndicate",cash:invs.reduce((a,i)=>a+Number(i.cash_invested),0),equity:invs.reduce((a,i)=>a+Number(i.equity),0),currentValue:invs.reduce((a,i)=>a+Number(i.current_value),0)};}else{const p=(players||[]).find(p=>p.id===invs[0].player_id);winner={playerId:invs[0].player_id,playerName:p?.display_name||"Winner",cash:Number(invs[0].cash_invested),equity:Number(invs[0].equity),currentValue:Number(invs[0].current_value)};}}
 return{id:c.id,name:c.name,tagline:c.tagline,sector:c.sector,founder:c.founder,askCash:c.askCash,askEquity:c.askEquity,summary:c.summary,story:c.story,businessModel:c.businessModel,risks:c.risks,facts:c.facts,qa:c.qa,submittedIds:companyBids.map(b=>bidEntityKey(b)),myBid:myBid?{cash:Number(myBid.cash),equity:Number(myBid.equity),passed:myBid.passed,syndicateId:myBid.syndicate_id}:null,finalist,feedback,result:["phase_result","intermission","finished"].includes(game.phase)?{actualDealCash:c.actualDealCash,actualDealEquity:c.actualDealEquity,outcome:c.outcome,winner}:null};}).filter(Boolean);
 const portfolio=new Map<string,number>(),invested=new Map<string,number>();for(const i of investments||[]){portfolio.set(i.player_id,(portfolio.get(i.player_id)||0)+Number(i.current_value));invested.set(i.player_id,(invested.get(i.player_id)||0)+Number(i.cash_invested));}
 const privateSyndicates=(syndicates||[]).filter(s=>mySyndicateIds.has(s.id)).map(s=>({id:s.id,name:s.name,status:s.status,leaderId:s.leader_id,isLeader:s.leader_id===player.id,members:(members||[]).filter(m=>m.syndicate_id===s.id).map(m=>({playerId:m.player_id,playerName:(players||[]).find(p=>p.id===m.player_id)?.display_name||"Player",share:Number(m.share),response:m.response})),messages:(messages||[]).filter(m=>m.syndicate_id===s.id).map(m=>({id:m.id,playerName:(players||[]).find(p=>p.id===m.player_id)?.display_name||"Player",body:m.body,createdAt:m.created_at}))}));
 return Response.json({gameId:game.id,roomCode:game.room_code,status:game.status,phase:game.phase,phaseNumber:game.phase_number,totalPhases:game.total_phases,companiesPerPhase:game.companies_per_phase,companies,syndicates:privateSyndicates,players:(players||[]).map(p=>({id:p.id,displayName:p.display_name,cash:Number(p.cash),ready:p.ready,isHost:p.is_host,portfolioValue:portfolio.get(p.id)||0,invested:invested.get(p.id)||0,netWorth:Number(p.cash)+(portfolio.get(p.id)||0)})),myPlayerId:player.id,isHost:player.is_host});
}catch(error){return jsonError(error,401);}}
